routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//------------------------- WELCOME PAGE -----------------------------------
Route::get('/', function () {
    return view('welcome');
});


//----------------------------- Authentication -----------------------------
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::any('/security-check', 'SessionController@switchSession');


Route::group(['middleware' => ['auth', 'CheckLoginStatus']], function ()
{

	Route::any('/dashboard', 'DashboardController@index');
	// -----------------------------------------------------------------------------
	//								RESOURCE GROUPS
	//------------------------------------------------------------------------------


	//*********************************** Subject Management *************************
	Route::resource('/subjectmgmt', 				'SubjectmgmtController');
	Route::get('/subjectmgmt/{id}/duplicate',       'SubjectmgmtController@duplicate' );


	//*********************************** Syudent Management *************************
	Route::resource('/studentmgmt', 'StudentmgmtController');
	Route::get('/studentmgmt/{id}/duplicate',       'StudentmgmtController@duplicate' );
	Route::get('/studentmgmt-classchoose', 'StudentmgmtController@chooseClass');
	Route::post('/studentlist-classwise', 'StudentmgmtController@generateStudentsClasswise');
	


	//*********************************** Class Management *************************
	Route::resource('/classmgmt', 'ClassmgmtController');


	//*********************************** Roll Number Management *************************
	Route::resource('/rollnumbermgmt', 'RollNumberController');



	//*********************************** Rank Calculator *************************
	Route::resource('/rankcalculator', 'RankCalculator');
	Route::get('/rankcalculator/{class}/{term}/generate', 'RankCalculator@rankCalculate');


	//*********************************** Mail *************************
	Route::get('/sendmailform', 'SendMail@sendmailreq');
	Route::post('/sendmailsubmit', 'SendMail@sendmailsubmit');


	//*********************************** Session Management *************************
	Route::resource('/sessionmgmt', 'SessionController');
	Route::get('/changesession', function (Request $request) {
													$request->session()->forget('valid_id');
												    return view('home');
												});

	//*********************************** CUSTOM ADMIT CARD *************************
	Route::resource('/customadmitcardmgmt', 'CustomAdmitCardController');
	Route::get('/customadmitcardmgmt/{id}/display',  'CustomAdmitCardController@display' );

	//*********************************** Upload Marks Term 1 *************************
	Route::resource('/uploadmarksterm1', 'UploadMarksTerm1Controller');
	Route::get('/term1entries/create/findclass',  'Term1EntriesController@findclass' );
	Route::post('/term1entries/create/findclass',  'Term1EntriesController@checkpresence' );


	//*********************************** Term 1 Marks Upload *************************
	Route::resource('/term1entries', 'Term1EntriesController');
	Route::get('/term1entries/create/findstudent',  'Term1EntriesController@findstudent' );
	Route::post('/term1entries/create/findstudent',  'Term1EntriesController@checkpresence' );

	//*********************************** Term 2 Marks Upload *************************
	Route::resource('/term2entries', 'Term2EntriesController');
	Route::get('/term2entries/create/findstudent',  'Term2EntriesController@findstudent' );
	Route::post('/term2entries/create/findstudent',  'Term2EntriesController@checkpresence' );

	//***************************** Result Date Management *************************
	Route::resource('/coscholastic', 'CoScholasticController');

	//*********************************** Result Date Management *************************
	Route::resource('/discipline', 'DisciplineController');

	//*********************************** Result Date Management *************************
	Route::resource('/resultdate', 'ResultDateController');





	//*************************************** ADMIT CARD ***************************
	Route::get('/admit-card',                	 'AdmitCardController@index' );
	Route::get('/admit-card/{id}/term1',         'AdmitCardController@term1' );
	Route::get('/admit-card/{id}/term2',         'AdmitCardController@term2' );
	// Route::get('/admit-card/custom-generate',    'AdmitCardController@createIndex' );



	//*************************************** ADMIT CARD ***************************
	Route::get('/reportcard/term1',                	'ReportCardController@term1' );
	Route::get('/reportcard/term2',                	'ReportCardController@term2' );
	Route::get('/reportcard/final',                	'ReportCardController@finalreportcard' );
	Route::any('/reportcard/generate',         		'ReportCardController@generateReportCard' );


	Route::any('/reportcard/bulk',         		'ReportCardController@bulk' );
	Route::any('/reportcard/bulk/{class}/{term}/generate',         		'ReportCardController@bulkgenerate' );



	//**************************Other Functionalities and Upgrade *********** */
	Route::any('/showmarks',         		'MarksController@index' );
	Route::any('/showmarks-submit',        	'MarksController@showTabulation' );
	// Route::any('/backup',        	        'BackupController@backup_tables' );
	
	Route::get('admin/login', 'AdminLoginController@getAdminLogin');
	Route::post('admin/login', ['as'=>'admin.auth','uses'=>'AdminLoginController@adminAuth']);
	
	Route::group(['middleware' => ['admin']], function () {
	Route::get('admin/dashboard', ['as'=>'admin.dashboard','uses'=>'AdminLoginController@dashboard']);
		
	Route::any('/upgrade',        	        'UpgradeController@index' );
	Route::any('/upcomingsession',        	 'UpgradeController@setupcomingsession' );
	Route::any('/upgradeclassselect',        	 'UpgradeController@showclasslist' );
	Route::any('/upgradestudentform',        	 'UpgradeController@showclasslistgenerate' );
	Route::any('/upgradestudentsubmit',        	 'UpgradeController@upgradestudents' );
	
	Route::any('/upgradesubjectsubmit',        	 'UpgradeController@upgradesubjects' );
	Route::any('/upgradedisciplinesubmit',       'UpgradeController@upgradedisciplines' );
	Route::any('/upgradecoscholasticsubmit',     'UpgradeController@upgradecoscholastics' );


	Route::get('/showallusers',     'MembersController@showusers' );
	Route::get('/adduserform',     'MembersController@adduserform' );
	Route::post('/addusersubmit',     'MembersController@adduser' );

	Route::get('/showalladmins',     'MembersController@showadmins' );
	Route::get('/addadminform',     'MembersController@addadminform' );
	Route::post('/addadminsubmit',     'MembersController@addadmin' );
	});
	
});




//------------------------------------------------------------------------------
//                               TEMPORARY ROUTES
//------------------------------------------------------------------------------
Route::get('/admit-card-sample', function()
	{
		return view('sample.admitcard');
	});

Route::get('/arrayinput', function () {  return view('sample.arrayinputs');  });
Route::post('/arrayinput',        'SampleController@store' );


Route::get('/setting', function()
	{
		
		return view('term1entries.createwithall');
	});


Route::get('/path', function()
	{
		return value(function() { return 'bar'; });
	});

Route::get('/testpage', function()
	{
		return view('sample.samplepage');
	});



Route::any( '{all}', function ( $missingRoute) {
    return 'Please go back and Proceed Again';
} )->where('all', '(.*)');

app/Studentmgmt.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Studentmgmt extends Model
{
    
}

app/Http/Controllers/StudentmgmtController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Studentmgmt;
use App\Classmgmt;

class StudentmgmtController extends Controller
{
    /**
     * Display a listing of the resource.
     * where('sessionid', Session('valid_id') )->get();
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $studentmgmt = Studentmgmt::where('sessionid', Session('valid_id') )->get();
        return View('studentmgmt.index')
            ->with('studentmgmt', $studentmgmt);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $classlist = Classmgmt::pluck('class_section');
        return view('studentmgmt.create')->with(['classlist' => $classlist ,]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'student_name' => 'required|min:3|max:150',
            'student_father_name' => 'required|min:3|max:150',
            'student_mother_name' => 'required|min:3|max:150',
            'student_address' => 'required|min:3|max:1000',
            'student_joining_date' => 'required',
            'student_dob' => 'required|min:6|max:15',
            'student_gender' => 'required|min:1|max:10',
            'student_mob1' => 'required|numeric|min:1000000000|max:9999999999',
        ]);

        $code = $request->input('admission_no')."-".Session('valid_id');
        if (Studentmgmt::where('code', $code)->exists())
        {
           $request->session()->flash('message', 'Requested Admission Number Already Exists, Please Verify it Before Proceeding!');
            return Redirect('studentmgmt');
        }
        else
        {
            $x = new Studentmgmt;
            $x->admission_no                        =       $request->input('admission_no');
            $x->student_name                        =       $request->input('student_name');
            $x->student_father_name                 =       $request->input('student_father_name');
            $x->student_mother_name                 =       $request->input('student_mother_name');
            $x->student_class_section               =       $request->input('student_class_section');
            $x->student_address                     =       $request->input('student_address');
            $x->student_joining_date                =       $request->input('student_joining_date');
            $x->student_images                      =       $request->input('student_images');
            $x->student_dob                         =       $request->input('student_dob');
            $x->student_gender                      =       $request->input('student_gender');
            $x->student_username                    =       $request->input('student_username');
            $x->student_password                    =       $request->input('student_password');
            $x->sessionid                           =       Session('valid_id');
            $x->student_email                       =       $request->input('student_email');
            $x->student_mob1                        =       $request->input('student_mob1');
            $x->student_mob2                        =       $request->input('student_mob2');
            $x->student_rollno                      =       $request->input('student_rollno');
            $x->code                                =       $code;

            $x->save();
        }

        $request->session()->flash('message', 'Successfully Created new Student Detail!');
        return Redirect('studentmgmt');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return 'Under Process';
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $classlist = Classmgmt::pluck('class_section');
        $studentdetail = Studentmgmt::find($id);
        return view('studentmgmt.edit')->with(['classlist' => $classlist ,'id' => $id, 'studentdetail' => $studentdetail,]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'admission_no' => 'required|min:0|max:99999',
            'student_name' => 'required|min:3|max:150',
            'student_father_name' => 'required|min:3|max:150',
            'student_mother_name' => 'required|min:3|max:150',
            'student_address' => 'required|min:3|max:1000',
            'student_joining_date' => 'required',
            'student_dob' => 'required|min:6|max:15',
            'student_gender' => 'required|min:1|max:10',
            'student_mob1' => 'required|numeric|min:1000000000|max:9999999999',
        ]);

        $code = $request->input('admission_no')."-".Session('valid_id');
        $x = Studentmgmt::find($id);
        $x->admission_no                        =       $request->input('admission_no');
        $x->student_name                        =       $request->input('student_name');
        $x->student_father_name                 =       $request->input('student_father_name');
        $x->student_mother_name                 =       $request->input('student_mother_name');
        $x->student_class_section               =       $request->input('student_class_section');
        $x->student_address                     =       $request->input('student_address');
        $x->student_joining_date                =       $request->input('student_joining_date');
        $x->student_images                      =       $request->input('student_images');
        $x->student_dob                         =       $request->input('student_dob');
        $x->student_gender                      =       $request->input('student_gender');
        $x->student_username                    =       $request->input('student_username');
        $x->student_password                    =       $request->input('student_password');
        $x->sessionid                           =       Session('valid_id');
        $x->student_email                       =       $request->input('student_email');
        $x->student_mob1                        =       $request->input('student_mob1');
        $x->student_mob2                        =       $request->input('student_mob2');
        $x->student_rollno                      =       $request->input('student_rollno');
        $x->code                                =       $code;

        $x->save();

        $request->session()->flash('message', 'Successfully Updated the Student Detail!');
        return Redirect('studentmgmt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $x = Studentmgmt::find($id);
        $x->delete();
        
        $request->session()->flash('message', 'Successfully Deleted the Student Details!');
        return Redirect('studentmgmt');
    }

    public function duplicate($id)
    {
        $classlist = Classmgmt::pluck('class_section');
        $studentdetail = Studentmgmt::find($id);
        return view('studentmgmt.duplicate')->with(['classlist' => $classlist ,'id' => $id, 'studentdetail' => $studentdetail,]);

    }

    public function chooseClass() {
        $classlist = Classmgmt::pluck('class_section');
        return view('studentmgmt.chooseclass')->with('classlist', $classlist);
    }

    public function generateStudentsClasswise(Request $request) {
        $cl = $request->input('student_class_section');
        $studentslist = Studentmgmt::where('student_class_section', $cl)->where('sessionid', Session('valid_id') )->get();
        return view('studentmgmt.index')
        ->with('studentmgmt', $studentslist);
    }
}

resources/views/studentmgmt/chooseclass.blade.php
@extends('layouts.app')

@section('content')

<div class="panel-heading">Choose Class</div>

<div class="panel-body">
    <form class="form-horizontal" method="POST" action="{{ URL('/') }}/studentlist-classwise">
        {{ csrf_field() }}


        <div class="form-group{{ $errors->has('student_class_section') ? ' has-error' : '' }}">
            <label for="student_class_section" class="col-md-4 control-label">Class Applicable</label>

            <div class="col-md-6">
                <select  id="student_class_section" class="form-control" name="student_class_section" >

                    @foreach ($classlist as $element)
                         <option value="{{$element}}"> {{$element}}</option>
                    @endforeach

                </select>

                @if ($errors->has('student_class_section'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_class_section') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <button type="submit" class="btn btn-success">
                    Proceed
                </button>
            </div>
        </div>

    </form>
</div>

@endsection

resources/views/studentmgmt/create.blade.php
@extends('layouts.app')

@section('content')

<div class="panel-heading">Register</div>

<div class="panel-body">
     <form class="form-horizontal" method="POST" action="{{ route('studentmgmt.store') }}">
        {{ csrf_field() }}


        <div class="form-group{{ $errors->has('admission_no') ? ' has-error' : '' }}">
            <label for="admission_no" class="col-md-4 control-label">Admission Number</label>

            <div class="col-md-6">
                <input id="admission_no" type="text" class="form-control" name="admission_no" value="{{ old('admission_no') }}" autofocus>

                @if ($errors->has('admission_no'))
                    <span class="help-block">
                        <strong>{{ $errors->first('admission_no') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_name') ? ' has-error' : '' }}">
            <label for="student_name" class="col-md-4 control-label">Student's Name</label>

            <div class="col-md-6">
                <input id="student_name" type="text" class="form-control" name="student_name" value="{{ old('student_name') }}" autofocus>

                @if ($errors->has('student_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_name') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_class_section') ? ' has-error' : '' }}">
            <label for="student_class_section" class="col-md-4 control-label">Class Applicable</label>

            <div class="col-md-6">
                <select  id="student_class_section" class="form-control" name="student_class_section" >
                    @foreach ($classlist as $element)
                         <option value="{{$element}}"> {{$element}}</option>
                    @endforeach
                                                   </select>

                @if ($errors->has('student_class_section'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_class_section') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_mother_name') ? ' has-error' : '' }}">
            <label for="student_mother_name" class="col-md-4 control-label">Mother's Name</label>

            <div class="col-md-6">
                <input id="student_mother_name" type="text" class="form-control" name="student_mother_name" value="{{ old('student_mother_name') }}" autofocus>

                @if ($errors->has('student_mother_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_mother_name') }}</strong>
                    </span>
                @endif
            </div>
        </div>



        <div class="form-group{{ $errors->has('student_father_name') ? ' has-error' : '' }}">
            <label for="student_father_name" class="col-md-4 control-label">Father's Name</label>

            <div class="col-md-6">
                <input id="student_father_name" type="text" class="form-control" name="student_father_name" value="{{ old('student_father_name') }}" autofocus>

                @if ($errors->has('student_father_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_father_name') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_address') ? ' has-error' : '' }}">
            <label for="student_address" class="col-md-4 control-label">Address</label>

            <div class="col-md-6">
                <input id="student_address" type="text" class="form-control" name="student_address" value="{{ old('student_address') }}" autofocus>

                @if ($errors->has('student_address'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_address') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_joining_date') ? ' has-error' : '' }}">
            <label for="student_joining_date" class="col-md-4 control-label">Date of Joining</label>

            <div class="col-md-6">
                <input id="student_joining_date" type="text" class="form-control" name="student_joining_date" value="{{ old('student_joining_date') }}" autofocus>

                @if ($errors->has('student_joining_date'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_joining_date') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_images') ? ' has-error' : '' }}">
            <label for="student_images" class="col-md-4 control-label">Student's Image</label>

            <div class="col-md-6">
                <input id="student_images" type="file" class="form-control" name="student_images" value="{{ old('student_images') }}" autofocus>

                @if ($errors->has('student_images'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_images') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_dob') ? ' has-error' : '' }}">
            <label for="student_dob" class="col-md-4 control-label">Date of Birth (dd-mm-yyyy)</label>

            <div class="col-md-6">
                <input id="student_dob" type="text" class="form-control" name="student_dob" value="{{ old('student_dob') }}" autofocus>

                @if ($errors->has('student_dob'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_dob') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_gender') ? ' has-error' : '' }}">
            <label for="student_gender" class="col-md-4 control-label">Student's Gender</label>

            <div class="col-md-6">
                <input id="student_gender" type="text" class="form-control" name="student_gender" value="{{ old('student_gender') }}" autofocus>

                @if ($errors->has('student_gender'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_gender') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_username') ? ' has-error' : '' }}">
            <label for="student_username" class="col-md-4 control-label">Student's Username</label>

            <div class="col-md-6">
                <input id="student_username" type="text" class="form-control" name="student_username" value="{{ old('student_username') }}" autofocus>

                @if ($errors->has('student_username'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_username') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_password') ? ' has-error' : '' }}">
            <label for="student_password" class="col-md-4 control-label">student's password</label>

            <div class="col-md-6">
                <input id="student_password" type="text" class="form-control" name="student_password" value="{{ old('student_password') }}" autofocus>

                @if ($errors->has('student_password'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_password') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_email') ? ' has-error' : '' }}">
            <label for="student_email" class="col-md-4 control-label">Student's Email</label>

            <div class="col-md-6">
                <input id="student_email" type="text" class="form-control" name="student_email" value="{{ old('student_email') }}" autofocus>

                @if ($errors->has('student_email'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_email') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('student_mob1') ? ' has-error' : '' }}">
            <label for="student_mob1" class="col-md-4 control-label">Student's Mobile 1</label>

            <div class="col-md-6">
                <input id="student_mob1" type="text" class="form-control" name="student_mob1" value="{{ old('student_mob1') }}" autofocus>

                @if ($errors->has('student_mob1'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_mob1') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_mob2') ? ' has-error' : '' }}">
            <label for="student_mob2" class="col-md-4 control-label">Student's Mobile 2</label>

            <div class="col-md-6">
                <input id="student_mob2" type="text" class="form-control" name="student_mob2" value="{{ old('student_mob2') }}" autofocus>

                @if ($errors->has('student_mob2'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_mob2') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('student_rollno') ? ' has-error' : '' }}">
            <label for="student_rollno" class="col-md-4 control-label">Students Roll No</label>

            <div class="col-md-6">
                <input id="student_rollno" type="text" class="form-control" name="student_rollno" value="{{ old('student_rollno') }}" autofocus>

                @if ($errors->has('student_rollno'))
                    <span class="help-block">
                        <strong>{{ $errors->first('student_rollno') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <button type="submit" class="btn btn-primary">
                    Update it
                </button>
            </div>
        </div>

    </form>
</div>

@endsection