routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//------------------------- WELCOME PAGE -----------------------------------
Route::get('/', function () {
    return view('welcome');
});


//----------------------------- Authentication -----------------------------
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::any('/security-check', 'SessionController@switchSession');


Route::group(['middleware' => ['auth', 'CheckLoginStatus']], function ()
{

	Route::any('/dashboard', 'DashboardController@index');
	// -----------------------------------------------------------------------------
	//								RESOURCE GROUPS
	//------------------------------------------------------------------------------


	//*********************************** Subject Management *************************
	Route::resource('/subjectmgmt', 				'SubjectmgmtController');
	Route::get('/subjectmgmt/{id}/duplicate',       'SubjectmgmtController@duplicate' );


	//*********************************** Syudent Management *************************
	Route::resource('/studentmgmt', 'StudentmgmtController');
	Route::get('/studentmgmt/{id}/duplicate',       'StudentmgmtController@duplicate' );
	Route::get('/studentmgmt-classchoose', 'StudentmgmtController@chooseClass');
	Route::post('/studentlist-classwise', 'StudentmgmtController@generateStudentsClasswise');
	


	//*********************************** Class Management *************************
	Route::resource('/classmgmt', 'ClassmgmtController');


	//*********************************** Roll Number Management *************************
	Route::resource('/rollnumbermgmt', 'RollNumberController');



	//*********************************** Rank Calculator *************************
	Route::resource('/rankcalculator', 'RankCalculator');
	Route::get('/rankcalculator/{class}/{term}/generate', 'RankCalculator@rankCalculate');


	//*********************************** Mail *************************
	Route::get('/sendmailform', 'SendMail@sendmailreq');
	Route::post('/sendmailsubmit', 'SendMail@sendmailsubmit');


	//*********************************** Session Management *************************
	Route::resource('/sessionmgmt', 'SessionController');
	Route::get('/changesession', function (Request $request) {
													$request->session()->forget('valid_id');
												    return view('home');
												});

	//*********************************** CUSTOM ADMIT CARD *************************
	Route::resource('/customadmitcardmgmt', 'CustomAdmitCardController');
	Route::get('/customadmitcardmgmt/{id}/display',  'CustomAdmitCardController@display' );

	//*********************************** Upload Marks Term 1 *************************
	Route::resource('/uploadmarksterm1', 'UploadMarksTerm1Controller');
	Route::get('/term1entries/create/findclass',  'Term1EntriesController@findclass' );
	Route::post('/term1entries/create/findclass',  'Term1EntriesController@checkpresence' );


	//*********************************** Term 1 Marks Upload *************************
	Route::resource('/term1entries', 'Term1EntriesController');
	Route::get('/term1entries/create/findstudent',  'Term1EntriesController@findstudent' );
	Route::post('/term1entries/create/findstudent',  'Term1EntriesController@checkpresence' );

	//*********************************** Term 2 Marks Upload *************************
	Route::resource('/term2entries', 'Term2EntriesController');
	Route::get('/term2entries/create/findstudent',  'Term2EntriesController@findstudent' );
	Route::post('/term2entries/create/findstudent',  'Term2EntriesController@checkpresence' );

	//***************************** Result Date Management *************************
	Route::resource('/coscholastic', 'CoScholasticController');

	//*********************************** Result Date Management *************************
	Route::resource('/discipline', 'DisciplineController');

	//*********************************** Result Date Management *************************
	Route::resource('/resultdate', 'ResultDateController');





	//*************************************** ADMIT CARD ***************************
	Route::get('/admit-card',                	 'AdmitCardController@index' );
	Route::get('/admit-card/{id}/term1',         'AdmitCardController@term1' );
	Route::get('/admit-card/{id}/term2',         'AdmitCardController@term2' );
	// Route::get('/admit-card/custom-generate',    'AdmitCardController@createIndex' );



	//*************************************** ADMIT CARD ***************************
	Route::get('/reportcard/term1',                	'ReportCardController@term1' );
	Route::get('/reportcard/term2',                	'ReportCardController@term2' );
	Route::get('/reportcard/final',                	'ReportCardController@finalreportcard' );
	Route::any('/reportcard/generate',         		'ReportCardController@generateReportCard' );


	Route::any('/reportcard/bulk',         		'ReportCardController@bulk' );
	Route::any('/reportcard/bulk/{class}/{term}/generate',         		'ReportCardController@bulkgenerate' );



	//**************************Other Functionalities and Upgrade *********** */
	Route::any('/showmarks',         		'MarksController@index' );
	Route::any('/showmarks-submit',        	'MarksController@showTabulation' );
	// Route::any('/backup',        	        'BackupController@backup_tables' );
	
	Route::get('admin/login', 'AdminLoginController@getAdminLogin');
	Route::post('admin/login', ['as'=>'admin.auth','uses'=>'AdminLoginController@adminAuth']);
	
	Route::group(['middleware' => ['admin']], function () {
	Route::get('admin/dashboard', ['as'=>'admin.dashboard','uses'=>'AdminLoginController@dashboard']);
		
	Route::any('/upgrade',        	        'UpgradeController@index' );
	Route::any('/upcomingsession',        	 'UpgradeController@setupcomingsession' );
	Route::any('/upgradeclassselect',        	 'UpgradeController@showclasslist' );
	Route::any('/upgradestudentform',        	 'UpgradeController@showclasslistgenerate' );
	Route::any('/upgradestudentsubmit',        	 'UpgradeController@upgradestudents' );
	
	Route::any('/upgradesubjectsubmit',        	 'UpgradeController@upgradesubjects' );
	Route::any('/upgradedisciplinesubmit',       'UpgradeController@upgradedisciplines' );
	Route::any('/upgradecoscholasticsubmit',     'UpgradeController@upgradecoscholastics' );


	Route::get('/showallusers',     'MembersController@showusers' );
	Route::get('/adduserform',     'MembersController@adduserform' );
	Route::post('/addusersubmit',     'MembersController@adduser' );

	Route::get('/showalladmins',     'MembersController@showadmins' );
	Route::get('/addadminform',     'MembersController@addadminform' );
	Route::post('/addadminsubmit',     'MembersController@addadmin' );
	});
	
});




//------------------------------------------------------------------------------
//                               TEMPORARY ROUTES
//------------------------------------------------------------------------------
Route::get('/admit-card-sample', function()
	{
		return view('sample.admitcard');
	});

Route::get('/arrayinput', function () {  return view('sample.arrayinputs');  });
Route::post('/arrayinput',        'SampleController@store' );


Route::get('/setting', function()
	{
		
		return view('term1entries.createwithall');
	});


Route::get('/path', function()
	{
		return value(function() { return 'bar'; });
	});

Route::get('/testpage', function()
	{
		return view('sample.samplepage');
	});



Route::any( '{all}', function ( $missingRoute) {
    return 'Please go back and Proceed Again';
} )->where('all', '(.*)');

app/Subjectmgmt.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Subjectmgmt extends Model
{
    
}

app/Http/Controllers/SubjectmgmtController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subjectmgmt;
use App\Classmgmt;

class SubjectmgmtController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjectmgmt = Subjectmgmt::where('sessionid', Session('valid_id') )->get();
        return View('subjectmgmt.index')
            ->with('subjectmgmt', $subjectmgmt);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $classlist = Classmgmt::pluck('class_section');
        return view('subjectmgmt.create')->with(['classlist' => $classlist ,]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'subjectcode' => 'required|max:190',
            'subject_name' => 'required|max:50',
            'class_applicable' => 'required',
            'term1_unittest' => 'required|numeric|min:0|max:1000',
            'term1_exam' => 'required|numeric|min:0|max:1000',
            'term2_unittest' => 'required|numeric|min:0|max:1000',
            'term2_exam' => 'required|numeric|min:0|max:1000',
        ]);

        $x = new Subjectmgmt;
        $x->subject_code                =       $request->input('subjectcode');
        $x->subject_name                =       $request->input('subject_name');
        $x->class_applicable            =       $request->input('class_applicable');
        $x->extra                       =       $request->input('extra');
        $x->term1_unittest              =       $request->input('term1_unittest');
        $x->term1_exam                  =       $request->input('term1_exam');
        $x->term1_total                 =       $request->input('term1_unittest')
                                                + $request->input('term1_exam');
        $x->term2_unittest              =       $request->input('term2_unittest');
        $x->term2_exam                  =       $request->input('term2_exam');
        $x->term2_total                 =       $request->input('term2_unittest')
                                                + $request->input('term2_exam'); 
        $x->status                      =       $request->input('status');
        $x->optional                    =       $request->input('optional');
        $x->grand_total_marks           =       $request->input('term1_unittest')
                                                + $request->input('term1_exam')
                                                + $request->input('term2_unittest')
                                                + $request->input('term2_exam');
        $x->date_term1                  =       $request->input('date_term1');
        $x->date_term2                  =       $request->input('date_term2');
        $x->sessionid                   =       Session('valid_id');

        $x->save();

        $request->session()->flash('message', 'Successfully Created new Subject Detail!');
        return Redirect('subjectmgmt');
    }

    /**Session('valid_id') and Session('valid_period')
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $subjectmgmt = Subjectmgmt::find($id);
        return view('subjectmgmt.show')->with(['subjectmgmt' => $subjectmgmt,]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $classlist = Classmgmt::pluck('class_section');
        $subjectmgmt = Subjectmgmt::find($id);
        return view('subjectmgmt.edit')->with(['subjectmgmt' => $subjectmgmt, 'id' => $id, 'classlist' => $classlist, ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'subjectcode' => 'required|max:190',
            'subject_name' => 'required|max:50',
            'class_applicable' => 'required',
            'term1_unittest' => 'required|numeric|min:0|max:1000',
            'term1_exam' => 'required|numeric|min:0|max:1000',
            'term2_unittest' => 'required|numeric|min:0|max:1000',
            'term2_exam' => 'required|numeric|min:0|max:1000',
        ]);

        $x = Subjectmgmt::find($id);
        $x->subject_code                =       $request->input('subjectcode');
        $x->subject_name                =       $request->input('subject_name');
        $x->class_applicable            =       $request->input('class_applicable');
        $x->extra                       =       $request->input('extra');
        $x->term1_unittest              =       $request->input('term1_unittest');
        $x->term1_exam                  =       $request->input('term1_exam');
        $x->term1_total                 =       $request->input('term1_unittest')
                                                + $request->input('term1_exam');
        $x->term2_unittest              =       $request->input('term2_unittest');
        $x->term2_exam                  =       $request->input('term2_exam');
        $x->term2_total                 =       $request->input('term2_unittest')
                                                + $request->input('term2_exam'); 
        $x->status                      =       $request->input('status');
        $x->optional                    =       $request->input('optional');
        $x->grand_total_marks           =       $request->input('term1_unittest')
                                                + $request->input('term1_exam')
                                                + $request->input('term2_unittest')
                                                + $request->input('term2_exam');
        $x->date_term1                  =       $request->input('date_term1');
        $x->date_term2                  =       $request->input('date_term2');
        $x->sessionid                   =       Session('valid_id');
        $x->save();

        $request->session()->flash('message', 'Successfully Updated the Subject Details!');
        return Redirect('subjectmgmt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $x = Subjectmgmt::find($id);
        $x->delete();
        
        $request->session()->flash('message', 'Successfully Deleted the Subject Details!');
        return Redirect('subjectmgmt');
    }

    public function duplicate($id)
    {
        $classlist = Classmgmt::pluck('class_section');
        $subjectmgmt = Subjectmgmt::find($id);
        return view('subjectmgmt.duplicate')->with(['subjectmgmt' => $subjectmgmt, 'id' => $id, 'classlist' => $classlist, ]);
    }

}

resources/views/subjectmgmt/create.blade.php
@extends('layouts.app')
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
@section('content')

<div class="panel-heading">Register</div>

<div class="panel-body">
    <form class="form-horizontal" method="POST" action="{{ route('subjectmgmt.store') }}">
        {{ csrf_field() }}

        <div class="form-group{{ $errors->has('subjectcode') ? ' has-error' : '' }}">
            <label for="subjectcode" class="col-md-4 control-label">Subject Code</label>

            <div class="col-md-6">
                <input id="subjectcode" type="text" class="form-control" name="subjectcode" value="{{ old('subjectcode') }}" autofocus>

                @if ($errors->has('subjectcode'))
                    <span class="help-block">
                        <strong>{{ $errors->first('subjectcode') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('subject_name') ? ' has-error' : '' }}">
            <label for="subject_name" class="col-md-4 control-label">Subject Name</label>

            <div class="col-md-6">
                <input id="subject_name" type="text" class="form-control" name="subject_name" value="{{ old('subject_name') }}" autofocus>

                @if ($errors->has('subject_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('subject_name') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('class_applicable') ? ' has-error' : '' }}">
            <label for="class_applicable" class="col-md-4 control-label">Class Applicable</label>

            <div class="col-md-6">
                <select  id="class_applicable" class="form-control" name="class_applicable" >
                    @foreach ($classlist as $element)
                         <option value="{{$element}}"> {{$element}}</option>
                    @endforeach
                </select>

                @if ($errors->has('class_applicable'))
                    <span class="help-block">
                        <strong>{{ $errors->first('class_applicable') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('extra') ? ' has-error' : '' }}">
            <label for="extra" class="col-md-4 control-label">Any Comment</label>

            <div class="col-md-6">
                <input id="extra" type="text" class="form-control" name="extra" value="{{ old('extra') }}" autofocus>

                @if ($errors->has('extra'))
                    <span class="help-block">
                        <strong>{{ $errors->first('extra') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('term1_unittest') ? ' has-error' : '' }}">
            <label for="term1_unittest" class="col-md-4 control-label">Term1 Unit Test Max Marks</label>

            <div class="col-md-6">
                <input id="term1_unittest" type="text" class="form-control" name="term1_unittest" value="{{ old('term1_unittest') }}" autofocus>

                @if ($errors->has('term1_unittest'))
                    <span class="help-block">
                        <strong>{{ $errors->first('term1_unittest') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group{{ $errors->has('term1_exam') ? ' has-error' : '' }}">
            <label for="term1_exam" class="col-md-4 control-label">Term1 Exam Max Marks</label>

            <div class="col-md-6">
                <input id="term1_exam" type="text" class="form-control" name="term1_exam" value="{{ old('term1_exam') }}" autofocus>

                @if ($errors->has('term1_exam'))
                    <span class="help-block">
                        <strong>{{ $errors->first('term1_exam') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('term1_total') ? ' has-error' : '' }}">
            <label for="term1_total" class="col-md-4 control-label">Term1 Total Marks</label>

            <div class="col-md-6">
                <input id="term1_total" type="text" class="form-control" name="term1_total" value="{{ old('term1_total') }}" autofocus disabled>

                @if ($errors->has('term1_total'))
                    <span class="help-block">
                        <strong>{{ $errors->first('term1_total') }}</strong>
                    </span>
                @endif
            </div>
        </div>



        <div class="form-group{{ $errors->has('term2_unittest') ? ' has-error' : '' }}">
            <label for="term2_unittest" class="col-md-4 control-label">Term2 Unit Test Max Marks</label>

            <div class="col-md-6">
                <input id="term2_unittest" type="text" class="form-control" name="term2_unittest" value="{{ old('term2_unittest') }}" autofocus>

                @if ($errors->has('term2_unittest'))
                    <span class="help-block">
                        <strong>{{ $errors->first('term2_unittest') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        
        <div class="form-group{{ $errors->has('term2_exam') ? ' has-error' : '' }}">
            <label for="term2_exam" class="col-md-4 control-label">Term2 Exam Max Marks</label>

            <div class="col-md-6">
                <input id="term2_exam" type="text" class="form-control" name="term2_exam" value="{{ old('term2_exam') }}" autofocus>

                @if ($errors->has('term2_exam'))
                    <span class="help-block">
                        <strong>{{ $errors->first('term2_exam') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('term2_total') ? ' has-error' : '' }}">
            <label for="term2_total" class="col-md-4 control-label">Term2 Total Max Marks</label>

            <div class="col-md-6">
                <input id="term2_total" type="text" class="form-control" name="term2_total" value="{{ old('term2_total') }}" autofocus disabled>

                @if ($errors->has('term2_total'))
                    <span class="help-block">
                        <strong>{{ $errors->first('term2_total') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
            <label for="status" class="col-md-4 control-label">Status</label>

            <div class="col-md-6">
                <input id="status" type="text" class="form-control" name="status" value="{{ old('status') }}" autofocus>

                @if ($errors->has('status'))
                    <span class="help-block">
                        <strong>{{ $errors->first('status') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('grand_total_marks') ? ' has-error' : '' }}">
            <label for="grand_total_marks" class="col-md-4 control-label">Grand Total Max Marks</label>

            <div class="col-md-6">
                <input id="grand_total_marks" type="text" class="form-control" name="grand_total_marks" value="{{ old('grand_total_marks') }}" autofocus disabled>

                @if ($errors->has('grand_total_marks'))
                    <span class="help-block">
                        <strong>{{ $errors->first('grand_total_marks') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('optional') ? ' has-error' : '' }}">
            <label for="optional" class="col-md-4 control-label">Optional (If any)</label>

             <div class="col-md-6">
                 <select  id="optional" class="form-control" name="optional" >
                         <option value="both test and exam"> Both test and exam</option>
                         <option value="only test"> only test</option>
                         <option value="only exam"> only exam</option>
                                                 </select>

                @if ($errors->has('optional'))
                    <span class="help-block">
                        <strong>{{ $errors->first('optional') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('date_term1') ? ' has-error' : '' }}">
            <label for="date_term1" class="col-md-4 control-label">Term 1 Exam Date (dd-mm-yyyy)</label>

            <div class="col-md-6">
                <input id="date_term1" type="text" class="form-control" name="date_term1" value="{{ old('date_term1') }}" autofocus>

                @if ($errors->has('date_term1'))
                    <span class="help-block">
                        <strong>{{ $errors->first('date_term1') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('date_term2') ? ' has-error' : '' }}">
            <label for="date_term2" class="col-md-4 control-label">Term 2 Exam Date (dd-mm-yyyy)</label>

            <div class="col-md-6">
                <input id="date_term2" type="text" class="form-control" name="date_term2" value="{{ old('date_term2') }}" autofocus>

                @if ($errors->has('date_term2'))
                    <span class="help-block">
                        <strong>{{ $errors->first('date_term2') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <button type="submit" class="btn btn-primary">
                    Register
                </button>
            </div>
        </div>

    </form>
</div>


<input id="term1_total_hidden" type="hidden" name="term1_total_hidden" value="0">
<input id="term2_total_hidden" type="hidden" name="term2_total_hidden" value="0">
<input id="grand_total_hidden" type="hidden" name="term2_total_hidden" value="0">

<script type="text/javascript">
  $(document).ready(function()
  {

  
        document.getElementById("term1_unittest").onkeyup = function() { myFunction(); };
        document.getElementById("term1_exam").onkeyup = function() { myFunction(); };

            function myFunction()
                {
                var x = document.getElementById("term1_unittest");
                var y = document.getElementById("term1_exam");
                var term1display = document.getElementById("term1_total");
                var term1hidden = document.getElementById("term1_total_hidden");
                var t1 = (parseInt(term1hidden.value) + parseInt(x.value) + parseInt(y.value));
                term1display.value = t1;

                var term2display = document.getElementById("term2_total");
                var grandhidden = document.getElementById("grand_total_hidden");
                var granddisplay = document.getElementById("grand_total_marks");
                var t2 = (parseInt(t1) + parseInt(grandhidden.value) + parseInt(term2display.value));
                granddisplay.value = t2;
                }



        document.getElementById("term2_unittest").onkeyup = function() { myFunction2(); };
        document.getElementById("term2_exam").onkeyup = function() { myFunction2(); };

            function myFunction2()
                {
                var x = document.getElementById("term2_unittest");
                var y = document.getElementById("term2_exam");
                var term2display = document.getElementById("term2_total");
                var term2hidden = document.getElementById("term2_total_hidden");
                var t1 = (parseInt(term2hidden.value) + parseInt(x.value) + parseInt(y.value));
                term2display.value = t1;

                var term1display = document.getElementById("term1_total");
                var grandhidden = document.getElementById("grand_total_hidden");
                var granddisplay = document.getElementById("grand_total_marks");
                var t2 = (parseInt(t1) + parseInt(grandhidden.value) + parseInt(term1display.value));
                granddisplay.value = t2;
                }   
    });    
</script>


@endsection

resources/views/subjectmgmt/index.blade.php
@extends('layouts.app')

@section('content')

<!-- will be used to show any messages -->
@if(Session('message'))
    <div class="alert alert-info">{{ Session('message') }}</div>
@endif

<h3>Showing the Details of Registered Subjects  </h3>

<a href="{{ URL::to('subjectmgmt/create') }}">
    <button type="button" class="btn btn-primary" style="margin: 10px 0px 0px 10px;">Register New Subject</button>
</a>



<div class="panel-body" style="overflow-x: scroll;">
    <table width="100%" class="table table-striped table-bordered table-hover" id="AdvancedTable">
            <thead>
                <th> ID </th>
                <th>  </th>
                <th></th>
                <th></th>
                <th> Subject Code </th>
                <th> Subject Name </th>
                <th> Class Applicable </th>
                <th> Term1 Unit Test Max </th>
                <th> Term1 Exam Max </th>
                <th> Term1 Total </th>
                <th> Term2 Unit Test Max </th>
                <th> Term2 Exam Max </th>
                <th> Term2 Total </th>
                <th> Status </th>
                <th> Grand Total Marks </th>
                <th> Exam Date Term1 </th>
                <th> Exam Date Term2 </th>
                <th> Session ID </th>
                
            </thead>
        @foreach ($subjectmgmt as $element)
            <tr>
                <td> {{ $element->id }} </td> 

                    <td> 
                        <a href="{{ URL::to('subjectmgmt/' . $element->id . '/edit') }}">
                            <input type="button" class="btn btn-info  btn-sm" name="" id="" value="Edit">
                        </a>   
                    
                    </td>

                    <td> 
                        <a href="{{ URL::to('subjectmgmt/' . $element->id . '/duplicate') }}">
                            <input type="button" class="btn btn-warning  btn-sm" name="" id="" value="Duplicate">
                        </a>  
                    
                    </td>

                    <td>
                    <form method="POST" action="{{ URL('subjectmgmt') }}/{{$element->id}}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="DELETE">
                    <input type="submit" class="btn btn-danger  btn-sm" name="submit" id="{{$element->id}}" value="Delete">
                    </form>

                    </td>
                    
                <td> {{ $element->subject_code }} </td> 
                <td> {{ $element->subject_name }} </td>
                <td> {{ $element->class_applicable }} </td>
                <td> {{ $element->term1_unittest }} </td>
                <td> {{ $element->term1_exam }} </td>
                <td> {{ $element->term1_total }} </td>
                <td> {{ $element->term2_unittest }} </td>
                <td> {{ $element->term2_exam }} </td>
                <td> {{ $element->term2_total }} </td>
                <td> {{ $element->status }} </td>
                <td> {{ $element->grand_total_marks }} </td>
                <td> {{ $element->date_term1 }} </td>
                <td> {{ $element->date_term2 }} </td>
                <td> {{ $element->sessionid }} </td>

                
                
            </tr>
        @endforeach
    </table>
</div>


@endsection